import Head from "next/head";
import Navbar from "../../components/Navbar";
import Main from "../../components/Main";
import About from "../../components/About";
import Skills from "../../components/Skills";
import Contact from "../../components/Contact";
import Experience from "../../components/Experience";
import SkillGrid from "../../components/Skills";
{
  /*import Resume from 'components/Resume'*/
}

export default function Home() {
  return (
    <div>
      <Head>
        <title>Tanuja Pyneni Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/navbarLogo.png" />
      </Head>
      <Navbar />
      <Main />
      <About />
      <Experience />
      <Skills />
      {/* <SkillGrid /> */}
      {/*<Resume/>*/}
      <Contact />
    </div>
  );
}
